"use client";

import { useRef, useState } from "react";
import { BookUp2, CheckCircle2, FileCode2, LoaderCircle, Upload, X } from "lucide-react";
import { apiFetch } from "@/lib/client-api";

type Preview = { title: string; authors: string; venue: string; year: number | null; doi: string | null; abstract: string; keywords: string; raw: string; identity: string; duplicateId: string | null };

export function BibtexImport({ open, onClose, onImported }: { open: boolean; onClose: () => void; onImported: () => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const [items, setItems] = useState<Preview[]>([]); const [selected, setSelected] = useState(new Set<number>()); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [strategy, setStrategy] = useState<"skip" | "merge">("skip");
  if (!open) return null;
  async function read(file?: File) { if (!file) return; setBusy(true); setError(""); try { const bibtex = await file.text(); const data = await apiFetch<{ items: Preview[] }>("/api/bibtex/preview", { method: "POST", body: JSON.stringify({ bibtex }) }); setItems(data.items); setSelected(new Set(data.items.map((_, index) => index))); } catch (e) { setError(e instanceof Error ? e.message : "读取失败"); } finally { setBusy(false); } }
  async function runImport() { setBusy(true); setError(""); try { const chosen = items.filter((_, index) => selected.has(index)); const result = await apiFetch<{ created: number; updated: number; skipped: number }>("/api/bibtex/import", { method: "POST", body: JSON.stringify({ items: chosen, duplicateStrategy: strategy }) }); alert(`导入完成：新增 ${result.created}，更新 ${result.updated}，跳过 ${result.skipped}`); onImported(); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "导入失败"); } finally { setBusy(false); } }
  return <div className="sheet-scrim"><section className="sheet-panel import-sheet" role="dialog" aria-modal="true" aria-label="导入 BibTeX"><header><div><h2>导入 BibTeX</h2><p>先预览和去重，再写入论文库。</p></div><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={20} /></button></header>
    {!items.length ? <button className="drop-zone" onClick={() => fileRef.current?.click()} disabled={busy}><span>{busy ? <LoaderCircle className="spin" size={28} /> : <FileCode2 size={28} />}</span><strong>{busy ? "正在解析…" : "选择 .bib 文件"}</strong><p>单次最多 5 MB；支持中文作者与常见 BibTeX 字段。</p><input ref={fileRef} type="file" accept=".bib,text/plain" hidden onChange={(e) => read(e.target.files?.[0])} /></button> : <><div className="import-toolbar"><label><input type="checkbox" checked={selected.size === items.length} onChange={(e) => setSelected(e.target.checked ? new Set(items.map((_, i) => i)) : new Set())} /> 全选 {items.length} 条</label><select value={strategy} onChange={(e) => setStrategy(e.target.value as "skip" | "merge")}><option value="skip">重复时跳过</option><option value="merge">重复时更新元数据</option></select></div><div className="import-list">{items.map((item, index) => <label key={`${item.identity}-${index}`} className={item.duplicateId ? "duplicate" : ""}><input type="checkbox" checked={selected.has(index)} onChange={(e) => { const next = new Set(selected); e.target.checked ? next.add(index) : next.delete(index); setSelected(next); }} /><div><strong>{item.title}</strong><p>{item.authors || "作者未知"} · {item.venue || "载体未知"} · {item.year ?? "年份未知"}</p></div>{item.duplicateId ? <span className="status-badge warn">可能重复</span> : <span className="status-badge success"><CheckCircle2 size={13} />新记录</span>}</label>)}</div></>}
    {error && <p className="form-error" role="alert">{error}</p>}<footer><button className="button ghost" onClick={onClose}>取消</button>{items.length > 0 && <button className="button primary" onClick={runImport} disabled={busy || !selected.size}>{busy ? <LoaderCircle className="spin" size={16} /> : <Upload size={16} />}导入 {selected.size} 条</button>}</footer>
  </section></div>;
}
