"use client";

import { useEffect, useState } from "react";
import { AlertCircle, Award, Check, CheckCircle2, Pencil, Plus, Scale, Target, Trash2, X } from "lucide-react";
import { apiFetch, formatDate } from "@/lib/client-api";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";

type Metric = Record<string, unknown> & { id: string; name: string; current: number; target: number; ratio: number; met: boolean };
type Cycle = Record<string, unknown> & { id: string; title: string; progress: number; requiredGaps: number; metrics: Metric[] };

export function PromotionView() {
  const [cycles, setCycles] = useState<Cycle[]>([]); const [cycleOpen, setCycleOpen] = useState(false); const [metricOpen, setMetricOpen] = useState(false); const [activeCycle, setActiveCycle] = useState(""); const [editingMetricId, setEditingMetricId] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [cycle, setCycle] = useState({ title: "", targetRole: "", startsAt: "", dueAt: "", notes: "" });
  const [metric, setMetric] = useState({ category: "科研成果", name: "", metricType: "count", sourceType: "manual", targetValue: "1", manualValue: "0", weight: "1", required: false, statusFilter: "", evidenceNotes: "" });
  function load() { apiFetch<{ items: Cycle[] }>("/api/promotion/cycles").then((data) => setCycles(data.items)); }
  useEffect(load, []);
  async function createCycle(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await apiFetch("/api/promotion/cycles", { method: "POST", body: JSON.stringify({ ...cycle, status: "active", startsAt: cycle.startsAt || null, dueAt: cycle.dueAt || null }) }); setCycleOpen(false); setCycle({ title: "", targetRole: "", startsAt: "", dueAt: "", notes: "" }); load(); } finally { setBusy(false); } }
  function resetMetric() { setMetric({ category: "科研成果", name: "", metricType: "count", sourceType: "manual", targetValue: "1", manualValue: "0", weight: "1", required: false, statusFilter: "", evidenceNotes: "" }); setEditingMetricId(null); }
  function openCreateMetric(cycleId: string) { setActiveCycle(cycleId); resetMetric(); setMetricOpen(true); }
  function openEditMetric(item: Metric) { let filter: Record<string, unknown> = {}; try { filter = item.source_filter ? JSON.parse(String(item.source_filter)) : {}; } catch {} setActiveCycle(String(item.cycle_id ?? "")); setEditingMetricId(item.id); setMetric({ category: String(item.category ?? "科研成果"), name: item.name, metricType: String(item.metric_type ?? "count"), sourceType: String(item.source_type ?? "manual"), targetValue: String(item.target_value ?? item.target ?? 1), manualValue: String(item.manual_value ?? item.current ?? 0), weight: String(item.weight ?? 1), required: Boolean(item.required), statusFilter: String(filter.status ?? ""), evidenceNotes: String(item.evidence_notes ?? "") }); setMetricOpen(true); }
  async function saveMetric(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { const payload = { category: metric.category, name: metric.name, metricType: metric.metricType, sourceType: metric.sourceType, targetValue: Number(metric.targetValue), manualValue: Number(metric.manualValue), weight: Number(metric.weight), required: metric.required, sourceFilter: metric.statusFilter ? { status: metric.statusFilter } : null, evidenceNotes: metric.evidenceNotes || null }; if (editingMetricId) await apiFetch(`/api/promotion/metrics/${editingMetricId}`, { method: "PATCH", body: JSON.stringify(payload) }); else await apiFetch("/api/promotion/metrics", { method: "POST", body: JSON.stringify({ cycleId: activeCycle, ...payload }) }); setMetricOpen(false); resetMetric(); load(); } finally { setBusy(false); } }
  async function updateManual(item: Metric, value: number) { await apiFetch(`/api/promotion/metrics/${item.id}`, { method: "PATCH", body: JSON.stringify({ manualValue: value }) }); load(); }
  async function removeMetric(id: string) { if (!confirm("删除这个晋升指标？")) return; await apiFetch(`/api/promotion/metrics/${id}`, { method: "DELETE" }); load(); }
  return <div className="promotion-page"><PageHeader title="晋升管理" description="把评审条件转化为持续更新的证据清单与差距视图。" actions={<button className="button primary" onClick={() => setCycleOpen(true)}><Plus size={16} />新建评审周期</button>} />
    {cycles.length ? <div className="promotion-stack">{cycles.map((item) => <section className="promotion-cycle" key={item.id}><header><div className="promotion-dial" style={{ "--progress": `${item.progress}%` } as React.CSSProperties}><strong>{item.progress}%</strong><span>完成度</span></div><div><span className="status-badge status-active">{String(item.status) === "active" ? "当前周期" : String(item.status)}</span><h2>{item.title}</h2><p>{String(item.target_role ?? "未设置目标职级")} · {item.due_at ? `${formatDate(String(item.due_at))} 截止` : "未设置截止日期"}</p></div><div className="cycle-summary"><span><Target size={17} /><strong>{item.metrics.length}</strong> 项指标</span><span className={item.requiredGaps ? "warn" : "ok"}>{item.requiredGaps ? <AlertCircle size={17} /> : <CheckCircle2 size={17} />}<strong>{item.requiredGaps}</strong> 个必达缺口</span></div><button className="button secondary" onClick={() => openCreateMetric(item.id)}><Plus size={15} />添加指标</button></header>
          <div className="metrics-table"><div className="metrics-head"><span>指标与来源</span><span>当前 / 目标</span><span>权重</span><span>完成度</span><span /></div>{item.metrics.length ? item.metrics.map((m) => <div className="metric-row" key={m.id}><div><span className="metric-icon">{m.required ? <Target size={17} /> : <Scale size={17} />}</span><div><strong>{m.name}</strong><small>{String(m.category)} · {String(m.source_type) === "manual" ? "手工记录" : `自动汇总 ${m.source_type}`}{m.required ? " · 必达" : ""}</small></div></div><div>{String(m.source_type) === "manual" ? <input className="metric-value-input" type="number" defaultValue={m.current} onBlur={(e) => updateManual(m, Number(e.target.value))} /> : <strong>{m.current}</strong>}<span> / {m.target}</span></div><div>{Number(m.weight).toFixed(1)}</div><div><div className="progress-track"><i style={{ width: `${Math.round(m.ratio * 100)}%` }} /></div><span>{Math.round(m.ratio * 100)}%</span></div><div className="metric-row-actions"><button className="icon-button" aria-label="编辑指标" title="编辑指标" onClick={() => openEditMetric(m)}><Pencil size={15} /></button><button className="icon-button danger" aria-label="删除指标" title="删除指标" onClick={() => removeMetric(m.id)}><Trash2 size={15} /></button></div></div>) : <div className="inline-empty"><Award size={22} /><p>添加论文、项目、专利或手工指标，开始计算差距。</p></div>}</div>
        </section>)}</div> : <EmptyState icon={Award} title="建立一个晋升评审周期" description="按你所在单位的规则配置必达项与加分项，工作台会从科研记录中自动汇总。" action={<button className="button primary" onClick={() => setCycleOpen(true)}><Plus size={16} />新建评审周期</button>} />}
    {cycleOpen && <div className="sheet-scrim"><section className="sheet-panel"><header><div><h2>新建评审周期</h2><p>记录目标职级和预计申报时间。</p></div><button className="icon-button" onClick={() => setCycleOpen(false)}><X size={20} /></button></header><form onSubmit={createCycle}><div className="form-grid"><label className="wide"><span>周期名称<b>*</b></span><input value={cycle.title} onChange={(e) => setCycle({ ...cycle, title: e.target.value })} placeholder="例如：2027 年副教授评审" required /></label><label className="wide"><span>目标职级</span><input value={cycle.targetRole} onChange={(e) => setCycle({ ...cycle, targetRole: e.target.value })} /></label><label><span>开始日期</span><input type="date" value={cycle.startsAt} onChange={(e) => setCycle({ ...cycle, startsAt: e.target.value })} /></label><label><span>申报截止</span><input type="date" value={cycle.dueAt} onChange={(e) => setCycle({ ...cycle, dueAt: e.target.value })} /></label><label className="wide"><span>说明</span><textarea rows={4} value={cycle.notes} onChange={(e) => setCycle({ ...cycle, notes: e.target.value })} /></label></div><footer><button type="button" className="button ghost" onClick={() => setCycleOpen(false)}>取消</button><button className="button primary" disabled={busy}>保存周期</button></footer></form></section></div>}
    {metricOpen && <div className="sheet-scrim"><section className="sheet-panel"><header><div><h2>{editingMetricId ? "编辑晋升指标" : "添加晋升指标"}</h2><p>{editingMetricId ? "修改指标定义、目标值、权重和证据说明。" : "可自动从科研记录计数，也可手工维护。"}</p></div><button className="icon-button" onClick={() => { setMetricOpen(false); resetMetric(); }}><X size={20} /></button></header><form onSubmit={saveMetric}><div className="form-grid"><label><span>指标类别</span><input value={metric.category} onChange={(e) => setMetric({ ...metric, category: e.target.value })} /></label><label><span>指标名称<b>*</b></span><input value={metric.name} onChange={(e) => setMetric({ ...metric, name: e.target.value })} required /></label><label><span>数据来源</span><select value={metric.sourceType} onChange={(e) => setMetric({ ...metric, sourceType: e.target.value })}><option value="manual">手工记录</option><option value="papers">论文</option><option value="projects">项目</option><option value="patents">专利</option><option value="growth">成长记录</option></select></label><label><span>状态筛选</span><input value={metric.statusFilter} onChange={(e) => setMetric({ ...metric, statusFilter: e.target.value })} placeholder="如 published，可留空" /></label><label><span>目标值</span><input type="number" min="0" step="any" value={metric.targetValue} onChange={(e) => setMetric({ ...metric, targetValue: e.target.value })} /></label><label><span>初始值</span><input type="number" min="0" step="any" value={metric.manualValue} onChange={(e) => setMetric({ ...metric, manualValue: e.target.value })} disabled={metric.sourceType !== "manual"} /></label><label><span>权重</span><input type="number" min="0" step="0.1" value={metric.weight} onChange={(e) => setMetric({ ...metric, weight: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={metric.required} onChange={(e) => setMetric({ ...metric, required: e.target.checked })} /><span>设为必达项</span></label><label className="wide"><span>证据说明</span><textarea rows={3} value={metric.evidenceNotes} onChange={(e) => setMetric({ ...metric, evidenceNotes: e.target.value })} /></label></div><footer><button type="button" className="button ghost" onClick={() => { setMetricOpen(false); resetMetric(); }}>取消</button><button className="button primary" disabled={busy}><Check size={16} />{editingMetricId ? "保存修改" : "保存指标"}</button></footer></form></section></div>}
  </div>;
}
