"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Archive, ArrowLeft, CalendarPlus, Check, Download, FileArchive, Link2, LoaderCircle, Paperclip, Plus, Trash2, UploadCloud, X } from "lucide-react";
import { apiFetch, formatBytes, formatDate } from "@/lib/client-api";
import { ModuleConfig, modules, statusLabel } from "@/lib/module-config";

type Detail = { item: Record<string, unknown>; tasks: Record<string, unknown>[]; revisions: { id: string; actor: string; snapshot: string; createdAt: string }[]; attachments: { id: string; originalName: string; mimeType: string; size: number; label: string | null; createdAt: string }[]; links: Record<string, unknown>[] };

export function RecordDetail({ config, id }: { config: ModuleConfig; id: string }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(""); const [taskTitle, setTaskTitle] = useState(""); const [taskDue, setTaskDue] = useState(""); const [busy, setBusy] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const [linkType, setLinkType] = useState(config.type === "projects" ? "papers" : "projects"); const [linkOptions, setLinkOptions] = useState<Record<string, unknown>[]>([]); const [linkId, setLinkId] = useState("");
  function load() { apiFetch<Detail>(`/api/records/${config.type}/${id}`).then(setData).catch((e) => setError(e.message)); }
  useEffect(load, [config.type, id]);
  useEffect(() => { if (linkType === config.type) return; apiFetch<{ items: Record<string, unknown>[] }>(`/api/records/${linkType}`).then((result) => { setLinkOptions(result.items); setLinkId(""); }).catch(() => setLinkOptions([])); }, [linkType, config.type]);
  const visibleFields = useMemo(() => config.fields.filter((field) => data?.item[field.key] != null && String(data.item[field.key]) !== ""), [config.fields, data]);
  async function addTask(event: React.FormEvent) { event.preventDefault(); if (!taskTitle.trim()) return; setBusy(true); try { await apiFetch("/api/tasks", { method: "POST", body: JSON.stringify({ title: taskTitle, dueAt: taskDue || null, entityType: config.type, entityId: id, status: "todo", priority: "medium", progress: 0, kind: "task" }) }); setTaskTitle(""); setTaskDue(""); load(); } finally { setBusy(false); } }
  async function toggleTask(task: Record<string, unknown>) { await apiFetch(`/api/tasks/${task.id}`, { method: "PATCH", body: JSON.stringify({ status: task.status === "done" ? "todo" : "done" }) }); load(); }
  async function upload(file?: File) { if (!file) return; setBusy(true); try { const form = new FormData(); form.set("file", file); form.set("entityType", config.type); form.set("entityId", id); await apiFetch("/api/attachments", { method: "POST", body: form }); load(); } catch (e) { alert(e instanceof Error ? e.message : "上传失败"); } finally { setBusy(false); if (fileRef.current) fileRef.current.value = ""; } }
  async function removeAttachment(attachmentId: string) { if (!confirm("确定删除这个附件？")) return; await apiFetch(`/api/attachments/${attachmentId}`, { method: "DELETE" }); load(); }
  async function createLink() { if (!linkId) return; await apiFetch("/api/links", { method: "POST", body: JSON.stringify({ sourceType: config.type, sourceId: id, targetType: linkType, targetId: linkId, relation: "related" }) }); load(); }
  async function removeLink(linkIdValue: string) { await apiFetch(`/api/links?id=${linkIdValue}`, { method: "DELETE" }); load(); }
  if (error) return <div className="load-error"><p>{error}</p><Link className="button secondary" href={`/${config.type}`}>返回列表</Link></div>;
  if (!data) return <div className="detail-skeleton"><span /><span /><span /></div>;
  return <div className="detail-page">
    <Link className="back-link" href={`/${config.type}`}><ArrowLeft size={17} />返回{config.title}</Link>
    <header className="detail-hero"><div><div className="detail-kinds"><span className={`status-badge status-${data.item.status}`}>{statusLabel[String(data.item.status)] ?? String(data.item.status ?? "记录")}</span>{Boolean(data.item.code) && <span>{String(data.item.code)}</span>}{Boolean(data.item.doi) && <span>DOI {String(data.item.doi)}</span>}</div><h1>{String(data.item.title)}</h1><p>{String(data.item.summary ?? data.item.abstract ?? data.item.evidence ?? "尚未补充摘要或说明。")}</p></div><div className="detail-rail"><span>最后更新</span><strong>{formatDate(String(data.item.updatedAt), true)}</strong><span>记录标识</span><code>{id.slice(0, 8)}</code></div></header>
    <div className="detail-layout"><main>
      <section className="detail-section"><div className="section-row"><div><h2>记录信息</h2><p>用于检索、统计和晋升证据汇总</p></div></div><dl className="detail-fields">{visibleFields.filter((field) => !["title", "summary", "abstract", "notes", "evidence"].includes(field.key)).map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{field.type === "date" ? formatDate(String(data.item[field.key])) : field.key === "status" ? statusLabel[String(data.item[field.key])] : String(data.item[field.key])}</dd></div>)}</dl>{Boolean(data.item.notes) && <div className="detail-notes"><h3>备注</h3><p>{String(data.item.notes)}</p></div>}</section>
      <section className="detail-section"><div className="section-row"><div><h2>任务与节点</h2><p>这些事项会同步到统一任务中心</p></div></div><form className="quick-task" onSubmit={addTask}><input value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} placeholder="添加下一步行动…" required /><input type="date" value={taskDue} onChange={(e) => setTaskDue(e.target.value)} aria-label="截止日期" /><button className="button primary" disabled={busy}><Plus size={16} />添加</button></form><div className="detail-task-list">{data.tasks.length ? data.tasks.map((task) => <button key={String(task.id)} onClick={() => toggleTask(task)} className={task.status === "done" ? "done" : ""}><span className="task-check">{task.status === "done" && <Check size={14} />}</span><div><strong>{String(task.title)}</strong><small>{task.due_at ? `${formatDate(String(task.due_at))} 截止` : "未设截止日期"}</small></div><span className={`status-badge priority-${task.priority}`}>{String(task.priority)}</span></button>) : <p className="subtle-empty">还没有关联任务。</p>}</div></section>
    </main><aside>
      <section className="side-section"><div className="section-row"><div><h2>附件材料</h2><p>{data.attachments.length} 个文件</p></div><button className="icon-button" onClick={() => fileRef.current?.click()} aria-label="上传附件">{busy ? <LoaderCircle className="spin" size={18} /> : <UploadCloud size={18} />}</button><input ref={fileRef} type="file" hidden accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.png,.jpg,.jpeg,.webp,.zip" onChange={(e) => upload(e.target.files?.[0])} /></div><div className="attachment-list">{data.attachments.length ? data.attachments.map((file) => <div key={file.id}><span><Paperclip size={16} /></span><div><strong>{file.originalName}</strong><small>{formatBytes(file.size)} · {formatDate(file.createdAt)}</small></div><a className="icon-button" href={`/api/attachments/${file.id}`} aria-label="下载"><Download size={16} /></a><button className="icon-button danger" onClick={() => removeAttachment(file.id)} aria-label="删除"><Trash2 size={15} /></button></div>) : <button className="upload-empty" onClick={() => fileRef.current?.click()}><FileArchive size={22} /><span>上传论文、表格或证明材料</span></button>}</div></section>
      <section className="side-section"><div className="section-row"><div><h2>关联成果</h2><p>建立研究链路</p></div></div><div className="link-builder"><select value={linkType} onChange={(e) => setLinkType(e.target.value)}>{Object.values(modules).filter((module) => module.type !== config.type).map((module) => <option value={module.type} key={module.type}>{module.singular}</option>)}</select><select value={linkId} onChange={(e) => setLinkId(e.target.value)}><option value="">选择记录</option>{linkOptions.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.title)}</option>)}</select><button className="button secondary" onClick={createLink} disabled={!linkId}><Link2 size={15} />建立关联</button></div><div className="related-list">{data.links.map((link) => <div key={String(link.id)}><span><Link2 size={15} /></span><div><strong>{String(link.otherTitle)}</strong><small>{String(link.otherType)}</small></div><button className="icon-button" onClick={() => removeLink(String(link.id))} aria-label="移除关联"><X size={15} /></button></div>)}</div></section>
      <section className="side-section"><div className="section-row"><div><h2>版本历史</h2><p>最近 {data.revisions?.length ?? 0} 次修改</p></div></div><div className="revision-list">{(data.revisions ?? []).length ? data.revisions.map((revision) => <div key={revision.id}><strong>{revision.actor === "mcp" ? "AI / MCP" : "用户修改"}</strong><small>{formatDate(revision.createdAt, true)}</small></div>) : <p className="subtle-empty">暂无历史版本。</p>}</div></section>
    </aside></div>
  </div>;
}
