"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArchiveRestore, Camera, Check, Database, Download, HardDrive, KeyRound, LoaderCircle, Palette, Save, Server, ShieldCheck, Trash2, Upload, UserRound } from "lucide-react";
import { apiFetch } from "@/lib/client-api";
import { PageHeader } from "@/components/page-header";
import { ThemeCenter } from "@/components/theme-center";
import { normalizeThemeConfig, type ThemeConfig } from "@/lib/theme-presets";

export function SettingsView() {
  const router = useRouter();
  const [profile, setProfile] = useState({ workbenchName: "电研工作台", displayName: "", institution: "", researchDirection: "", timezone: "Asia/Hong_Kong" }); const [theme, setTheme] = useState<ThemeConfig>(normalizeThemeConfig(null)); const [email, setEmail] = useState(""); const [saved, setSaved] = useState("");
  const [password, setPassword] = useState({ currentPassword: "", nextPassword: "", confirm: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [avatarVersion, setAvatarVersion] = useState(Date.now()); const [avatarMissing, setAvatarMissing] = useState(false); const restoreRef = useRef<HTMLInputElement>(null); const avatarRef = useRef<HTMLInputElement>(null);
  useEffect(() => { apiFetch<{ settings: typeof profile & { themePreset?: string; themeMode?: string; themeOverrides?: string }; user: { email: string } }>("/api/settings").then((data) => { setProfile({ workbenchName:data.settings.workbenchName || "电研工作台", displayName:data.settings.displayName, institution:data.settings.institution, researchDirection:data.settings.researchDirection, timezone:data.settings.timezone }); let overrides={}; try { overrides=JSON.parse(data.settings.themeOverrides ?? "{}"); } catch {} setTheme(normalizeThemeConfig({ preset:data.settings.themePreset as never, mode:data.settings.themeMode as never, overrides })); setEmail(data.user.email); }); }, []);
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await apiFetch("/api/settings", { method: "PATCH", body: JSON.stringify(profile) }); router.refresh(); setSaved("工作台与个人信息已保存"); setTimeout(() => setSaved(""), 2200); } catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setBusy(false); } }
  async function saveTheme() { setBusy(true); setError(""); try { await apiFetch("/api/settings", { method:"PATCH", body:JSON.stringify({ themePreset:theme.preset, themeMode:theme.mode, themeOverrides:JSON.stringify(theme.overrides) }) }); setSaved("主题设置已保存"); setTimeout(()=>setSaved(""),2200); } catch(e) { setError(e instanceof Error ? e.message : "主题保存失败"); } finally { setBusy(false); } }
  async function uploadAvatar(file?: File) { if (!file) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("file", file); await apiFetch("/api/profile/avatar", { method: "POST", body: form }); const version = Date.now(); setAvatarMissing(false); setAvatarVersion(version); window.dispatchEvent(new CustomEvent("profile-avatar-changed", { detail: { url: `/api/profile/avatar?v=${version}` } })); setSaved("头像已更新"); setTimeout(() => setSaved(""), 2200); } catch (e) { setError(e instanceof Error ? e.message : "头像上传失败"); } finally { setBusy(false); if (avatarRef.current) avatarRef.current.value = ""; } }
  async function removeAvatar() { setBusy(true); setError(""); try { await apiFetch("/api/profile/avatar", { method: "DELETE" }); setAvatarMissing(true); window.dispatchEvent(new CustomEvent("profile-avatar-changed", { detail: { url: null } })); setSaved("头像已移除"); setTimeout(() => setSaved(""), 2200); } catch (e) { setError(e instanceof Error ? e.message : "头像删除失败"); } finally { setBusy(false); } }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); setError(""); if (password.nextPassword !== password.confirm) { setError("两次输入的新密码不一致"); return; } setBusy(true); try { await apiFetch("/api/auth/password", { method: "POST", body: JSON.stringify({ currentPassword: password.currentPassword, nextPassword: password.nextPassword }) }); alert("密码已更新，请重新登录。"); window.location.href = "/login"; } catch (e) { setError(e instanceof Error ? e.message : "密码更新失败"); setBusy(false); } }
  async function restore(file?: File) { if (!file) return; if (!confirm("恢复仅适用于空白实例。确定校验并尝试恢复这个备份？")) return; setBusy(true); setError(""); try { const form = new FormData(); form.set("file", file); await apiFetch("/api/backup/restore", { method: "POST", body: form }); alert("恢复完成，页面将重新载入。"); window.location.reload(); } catch (e) { setError(e instanceof Error ? e.message : "恢复失败"); } finally { setBusy(false); if (restoreRef.current) restoreRef.current.value = ""; } }
  return <div className="settings-page"><PageHeader title="系统设置" description="管理主题外观、个人信息、登录安全、备份和部署状态。" />
    {error && <p className="form-error settings-error" role="alert">{error}</p>}{saved && <p className="save-toast"><Check size={15} />{saved}</p>}
    <div className="settings-layout"><nav className="settings-index"><a href="#appearance"><Palette size={17} />主题中心</a><a href="#profile"><UserRound size={17} />个人信息</a><a href="#security"><ShieldCheck size={17} />登录安全</a><a href="#backup"><Database size={17} />数据备份</a><a href="#deployment"><Server size={17} />部署状态</a></nav><main>
      <ThemeCenter value={theme} onChange={setTheme} onSave={saveTheme} saving={busy} />
      <section id="profile" className="settings-section"><header><span><UserRound size={19} /></span><div><h2>个人信息</h2><p>用于工作台中的称呼与科研语境。</p></div></header><div className="avatar-settings"><div className="avatar-preview">{avatarMissing ? <span>{(profile.displayName || email || "研").slice(0,1).toUpperCase()}</span> : <img src={`/api/profile/avatar?v=${avatarVersion}`} alt="头像" onError={() => setAvatarMissing(true)} />}</div><div><strong>个人头像</strong><p>支持 JPG、PNG、WebP，最大 2 MB。头像会随完整备份一起保存。</p><div className="avatar-actions"><button type="button" className="button secondary" onClick={() => avatarRef.current?.click()} disabled={busy}><Camera size={16} />上传头像</button><button type="button" className="button ghost" onClick={removeAvatar} disabled={busy || avatarMissing}><Trash2 size={15} />移除头像</button></div><input ref={avatarRef} type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={(e) => uploadAvatar(e.target.files?.[0])} /></div></div><form onSubmit={saveProfile}><div className="form-grid"><label className="wide"><span>工作台名称</span><input value={profile.workbenchName} onChange={(e) => setProfile({ ...profile, workbenchName: e.target.value })} maxLength={80} required placeholder="例如：电研工作台" /></label><label><span>显示名称</span><input value={profile.displayName} onChange={(e) => setProfile({ ...profile, displayName: e.target.value })} /></label><label><span>登录邮箱</span><input value={email} disabled /></label><label><span>机构</span><input value={profile.institution} onChange={(e) => setProfile({ ...profile, institution: e.target.value })} placeholder="可留空" /></label><label><span>研究方向</span><input value={profile.researchDirection} onChange={(e) => setProfile({ ...profile, researchDirection: e.target.value })} /></label><label><span>时区</span><select value={profile.timezone} onChange={(e) => setProfile({ ...profile, timezone: e.target.value })}><option value="Asia/Hong_Kong">Asia/Hong_Kong</option><option value="Asia/Shanghai">Asia/Shanghai</option><option value="UTC">UTC</option></select></label></div><div className="settings-actions"><button className="button primary" disabled={busy}><Save size={16} />保存信息</button></div></form></section>
      <section id="security" className="settings-section"><header><span><ShieldCheck size={19} /></span><div><h2>登录安全</h2><p>密码至少 12 位；修改后会撤销所有现有会话。</p></div></header><form onSubmit={changePassword}><div className="form-grid"><label className="wide"><span>当前密码</span><input type="password" autoComplete="current-password" value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} required /></label><label><span>新密码</span><input type="password" autoComplete="new-password" minLength={12} value={password.nextPassword} onChange={(e) => setPassword({ ...password, nextPassword: e.target.value })} required /></label><label><span>确认新密码</span><input type="password" autoComplete="new-password" minLength={12} value={password.confirm} onChange={(e) => setPassword({ ...password, confirm: e.target.value })} required /></label></div><div className="settings-actions"><button className="button secondary" disabled={busy}><KeyRound size={16} />修改密码</button></div></form></section>
      <section id="backup" className="settings-section"><header><span><Database size={19} /></span><div><h2>数据备份</h2><p>导出数据库、附件与校验清单，供迁移或灾难恢复使用。</p></div></header><div className="backup-actions"><a className="backup-option" href="/api/backup/export"><span><Download size={20} /></span><div><strong>下载完整备份</strong><p>生成 ZIP，包含结构化数据、附件与 SHA-256 校验值。</p></div></a><button className="backup-option" onClick={() => restoreRef.current?.click()} disabled={busy}><span>{busy ? <LoaderCircle className="spin" size={20} /> : <Upload size={20} />}</span><div><strong>恢复到空白实例</strong><p>当前实例存在业务数据时会拒绝恢复，防止覆盖。</p></div></button><input ref={restoreRef} type="file" hidden accept=".zip" onChange={(e) => restore(e.target.files?.[0])} /></div></section>
      <section id="deployment" className="settings-section"><header><span><Server size={19} /></span><div><h2>部署状态</h2><p>当前应用的持久化与运行约束。</p></div></header><dl className="deployment-grid"><div><dt><Activity size={16} />运行模式</dt><dd>单管理员 · 私有部署</dd></div><div><dt><HardDrive size={16} />数据库</dt><dd>SQLite WAL</dd></div><div><dt><ArchiveRestore size={16} />附件存储</dt><dd>服务器私有卷</dd></div><div><dt><ShieldCheck size={16} />会话</dt><dd>HttpOnly · SameSite</dd></div></dl></section>
    </main></div>
  </div>;
}
